// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGFNQvDO0pcMMWKNQxLCcueJ6YVxf3pik',
    appId: '1:980673510154:web:3ee4d99c37d28d190b18f3',
    messagingSenderId: '980673510154',
    projectId: 'my-portfolio-a478f',
    authDomain: 'my-portfolio-a478f.firebaseapp.com',
    databaseURL: 'https://my-portfolio-a478f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-portfolio-a478f.firebasestorage.app',
    measurementId: 'G-9SPWGCN89D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0EP8Nty_gvmrBfG2eeaPrN9BxzB92Jmw',
    appId: '1:980673510154:android:33492f65dadd95970b18f3',
    messagingSenderId: '980673510154',
    projectId: 'my-portfolio-a478f',
    databaseURL: 'https://my-portfolio-a478f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-portfolio-a478f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaXRQdztJornHZFCcGfPc6K9Dpla_9EPQ',
    appId: '1:980673510154:ios:0694400961ed76800b18f3',
    messagingSenderId: '980673510154',
    projectId: 'my-portfolio-a478f',
    databaseURL: 'https://my-portfolio-a478f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-portfolio-a478f.firebasestorage.app',
    iosBundleId: 'com.bandan.me.portfolio',
  );
}
